
```yaml
# pubspec.yaml - Add this to handle environment variables
flutter:
  uses-material-design: true
  assets:
    - images/

# Add this for environment variables
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"
```

Create a `.env` file in your project root:
```
SUPABASE_KEY=your_actual_supabase_anon_key_here
```